name: Code check
on: [push]
jobs:
  eslint-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
